[platformio]
default_envs = esp32-c3-supermini-plus

[env:esp32-c3-supermini-plus]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit VEML7700 Library@^2.1.6

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; If native USB upload does not start automatically, hold BOOT, press RESET,
; release RESET, then release BOOT and repeat the upload.
